// This file is generated by icon spritesheet generator

export type IconName =
  | "strike"
  | "quote"
  | "paragraph"
  | "italic"
  | "bold"

export const iconNames = [
  "strike",
  "quote",
  "paragraph",
  "italic",
  "bold",
] as const
